/*
Autores:
-Aarón Durán Sánchez
-Javier López de Lerma
-Mateo García Fuentes
-Carlos López Martínez


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokertrainer.view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Javi
 */
public class CardPanel extends javax.swing.JPanel {

    private ImageIcon card;
    private Image rescaledCard;
    private static final int CARD_HEIGHT = 64;
    private static final int CARD_WIDTH = 54;
    private static final ImageIcon DEFAULTCARD = new ImageIcon(CardPanel.class.getResource("img/behindCard.png"));

    /**
     * Creates new form CardPanel
     */
    
    public CardPanel() {
        //pensar en cambiarlo por null
        this(DEFAULTCARD);
    }
    
    public CardPanel(ImageIcon card) {
        this.setPreferredSize(new Dimension(CARD_WIDTH, CARD_HEIGHT));
        this.card = card;
        this.rescaledCard = card.getImage().getScaledInstance(CARD_WIDTH, CARD_HEIGHT, Image.SCALE_DEFAULT);
    }
    
    public ImageIcon getCard(){
        return card;
    }
    
    public Image getRescaledCard(){
        return rescaledCard;
    }
    
    public void setCard(ImageIcon card){
        if(card != null){
            this.card = card;
            this.rescaledCard = card.getImage();
            this.repaint();
        }
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(rescaledCard, 0, 0, this.getWidth(), this.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void disablePanel() {
        this.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
