/*
Autores:
-Aarón Durán Sánchez
-Javier López de Lerma
-Mateo García Fuentes
-Carlos López Martínez


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokertrainer.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Javi
 */
public class PlayerCards extends javax.swing.JPanel {

    /**
     * Creates new form PlayerInfo
     */
    public PlayerCards() {
        initComponents();
    }
    
    public void setCardsImages(ImageIcon card1, ImageIcon card2) {
        this.playerCard1.setCard(card1);
        this.playerCard2.setCard(card2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerCard2 = new pokertrainer.view.CardPanel();
        playerCard1 = new pokertrainer.view.CardPanel();

        setAutoscrolls(true);
        setOpaque(false);

        javax.swing.GroupLayout playerCard2Layout = new javax.swing.GroupLayout(playerCard2);
        playerCard2.setLayout(playerCard2Layout);
        playerCard2Layout.setHorizontalGroup(
            playerCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        playerCard2Layout.setVerticalGroup(
            playerCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout playerCard1Layout = new javax.swing.GroupLayout(playerCard1);
        playerCard1.setLayout(playerCard1Layout);
        playerCard1Layout.setHorizontalGroup(
            playerCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        playerCard1Layout.setVerticalGroup(
            playerCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(playerCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(playerCard2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pokertrainer.view.CardPanel playerCard1;
    private pokertrainer.view.CardPanel playerCard2;
    // End of variables declaration//GEN-END:variables

    void disablePanel() {
        this.playerCard1.disablePanel();
        this.playerCard2.disablePanel();
        this.setVisible(false);
    }
}
