/*
Autores:
-Aarón Durán Sánchez
-Javier López de Lerma
-Mateo García Fuentes
-Carlos López Martínez


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokertrainer.view;

import java.awt.Color;

/**
 *
 * @author Javi
 */
public class PlayerBet extends javax.swing.JPanel {

    /**
     * Creates new form PlayerInfo
     */
    public PlayerBet() {
        initComponents();
        playerBet.setForeground(Color.GREEN);
    }
    
    
    public void setBet(int bet) {
        if (bet != 0) playerBet.setText("" + bet);
        else playerBet.setText("");
    }
    
    public void setFoldBet(){
        playerBet.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerBet = new javax.swing.JLabel();

        setAutoscrolls(true);
        setOpaque(false);

        playerBet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        playerBet.setForeground(new java.awt.Color(0, 255, 0));
        playerBet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerBet.setText("1K");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerBet, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerBet, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel playerBet;
    // End of variables declaration//GEN-END:variables

    void disablePanel() {
        this.playerBet.setVisible(false);
        this.setVisible(false);
    }
}
