/*
Autores:
-Aarón Durán Sánchez
-Javier López de Lerma
-Mateo García Fuentes
-Carlos López Martínez


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokertrainer.view;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import pokertrainer.model.Role;

/**
 *
 * @author Javi
 */
public class PlayerInfo extends javax.swing.JPanel {
    
    private final Border turn = BorderFactory.createLineBorder(Color.yellow, 5, true);
    private final Border notTurn = BorderFactory.createLineBorder(new Color(240, 240, 240), 5, true);
    private final Border fold = BorderFactory.createLineBorder(Color.RED,5, true);
    private final Border win = BorderFactory.createLineBorder(Color.GREEN,5, true);

    /**
     * Creates new form PlayerInfo
     */
    public PlayerInfo() {
        initComponents();
    }
    
    
    public void setInfo(int money, String name, Role role) {
        setPlayerMoney(money);
        setPlayerName(name);
        setPlayerRole(role);
    }
    
    public void setPlayerMoney(int money) {
        playerMoney.setText(money + "");
    }
    
    private void setPlayerName(String name) {
        playerName.setText(name);
    }
    
    public void setPlayerRole(Role role) {
        playerRol.setText(role.toString());
    }
    
    public void showPanelTurnPlayer(){
        this.jPanel1.setBorder(turn);
    }
    
    public void disableShowPanelTurnPlayer(){
        this.jPanel1.setBorder(notTurn);
        this.update(this.getGraphics());
    }
    
    public void setFoldInfo() {
        this.jPanel1.setBorder(fold);
    }
    
    public void setWinnerInfo(){
        this.jPanel1.setBorder(win);
        this.update(this.getGraphics());
    }
    
    public void setMoneyZero(){
        this.playerMoney.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playerName = new javax.swing.JLabel();
        playerRol = new javax.swing.JLabel();
        playerMoney = new javax.swing.JLabel();

        setAutoscrolls(true);
        setOpaque(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 5, true));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setOpaque(false);

        playerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playerName.setForeground(new java.awt.Color(204, 204, 204));
        playerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerName.setText("PlayerName");

        playerRol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        playerRol.setForeground(new java.awt.Color(255, 255, 153));
        playerRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerRol.setText("Big Blind");

        playerMoney.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerMoney.setForeground(new java.awt.Color(255, 0, 0));
        playerMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerMoney.setText("113K");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playerMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(playerRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerMoney))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerMoney;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerRol;
    // End of variables declaration//GEN-END:variables

    void disablePanel() {
        this.jPanel1.setVisible(false);
        this.playerMoney.setVisible(false);
        this.playerName.setVisible(false);
        this.playerRol.setVisible(false);
        this.setVisible(false);
    }

    

    
}
