/*
Autores:
-Aarón Durán Sánchez
-Javier López de Lerma
-Mateo García Fuentes
-Carlos López Martínez


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokertrainer.view;

/**
 *
 * @author Javi
 */
public class PotPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerInfo
     */
    public PotPanel() {
        initComponents();
    }
    
    void setPot(int moneyPot) {
        potQuantity.setText(String.valueOf(moneyPot));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potQuantity = new javax.swing.JLabel();
        potImage = new javax.swing.JLabel();

        setAutoscrolls(true);
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        potQuantity.setBackground(new java.awt.Color(0, 0, 0));
        potQuantity.setForeground(new java.awt.Color(255, 255, 255));
        potQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potQuantity.setText("0");
        potQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        potQuantity.setOpaque(true);
        add(potQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 119, 20));

        potImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        potImage.setForeground(new java.awt.Color(240, 240, 240));
        potImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokertrainer/view/img/potImage.png"))); // NOI18N
        add(potImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 119, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel potImage;
    private javax.swing.JLabel potQuantity;
    // End of variables declaration//GEN-END:variables

   
}
